Разметка
zeckson/htmlacademy-nerds pull request #1
Opened 2020-09-28 21:44 UTC by webdotG

2020-09-29 09:26 UTC, zeckson requested changes
Очень хорошо. Почему-то забил на заглушки из задания, непонятно почему...
И много где есть лишние `section` не понял зачем ты их сделал, но пусть будут наверное тебе так будет проще ориентироваться. В будущем они могут снять дополнительные баллы при проверке по критерию за избыточную вёрстку.

2020-09-29 09:26 UTC, zeckson commented on index.html
> +  <title></title>
Тайтл куда-то пропал

2020-09-29 09:26 UTC, zeckson commented on index.html
> +    <a href="#"><img src="" alt="Nerds logo"></a>
По заданию должны быть заглушка:
```
Изображения вырезать не нужно — используйте вместо них заглушки, например: <img src="http://placehold.it/150x100">.
```
где заглушка?

2020-09-29 09:26 UTC, zeckson commented on index.html
> +  <section>
Почему `section`>`div` а не `ul`>`li`?

2020-09-29 09:26 UTC, zeckson commented on index.html
> +  <section>
Зачем тут оборачивающий `section`?

2020-09-29 09:26 UTC, zeckson commented on index.html
> +      <li><img src="" alt="html academy logo"></li>
По заданию должны быть заглушка:
```
Изображения вырезать не нужно — используйте вместо них заглушки, например: <img src="http://placehold.it/150x100">.
```
нет заглушки

2020-09-29 09:26 UTC, zeckson commented on index.html
> +      <li><img src="" alt="borodinsky logo"></li>
По заданию должны быть заглушка:
```
Изображения вырезать не нужно — используйте вместо них заглушки, например: <img src="http://placehold.it/150x100">.
```
нет заглушки

2020-09-29 09:26 UTC, zeckson commented on index.html
> +      <li><img src="" alt="pink logo"></li>
По заданию должны быть заглушка:
```
Изображения вырезать не нужно — используйте вместо них заглушки, например: <img src="http://placehold.it/150x100">.
```
нет заглушки

2020-09-29 09:26 UTC, zeckson commented on index.html
> +      <li><img src="" alt="mishka logo"></li>
По заданию должны быть заглушка:
```
Изображения вырезать не нужно — используйте вместо них заглушки, например: <img src="http://placehold.it/150x100">.
```
нет заглушки

2020-09-29 09:26 UTC, zeckson commented on index.html
> +      <button></button>
Что это такое?

2020-09-29 09:26 UTC, zeckson commented on index.html
> +    <li><a href="#"><img src="" alt="vk"></a></li>
По заданию должны быть заглушка:
```
Изображения вырезать не нужно — используйте вместо них заглушки, например: <img src="http://placehold.it/150x100">.
```
нет заглушки

2020-09-29 09:26 UTC, zeckson commented on index.html
> +    <li><a href="#"><img src="" alt="facebook"></a></li>
По заданию должны быть заглушка:
```
Изображения вырезать не нужно — используйте вместо них заглушки, например: <img src="http://placehold.it/150x100">.
```
нет заглушки

2020-09-29 09:26 UTC, zeckson commented on index.html
> +    <li><a href="#"><img src="" alt="instagram"></a></li>
По заданию должны быть заглушка:
```
Изображения вырезать не нужно — используйте вместо них заглушки, например: <img src="http://placehold.it/150x100">.
```
нет заглушки

2020-09-30 13:18 UTC, webdotG commented on index.html
> +  <title></title>
fix

2020-09-30 13:19 UTC, webdotG commented on index.html
> +    <a href="#"><img src="" alt="Nerds logo"></a>
fix

2020-09-30 13:19 UTC, webdotG commented on index.html
> +  <section>
временно для удобного различия

2020-09-30 13:19 UTC, webdotG commented on index.html
> +  <section>
временно для удобного различия

2020-09-30 13:19 UTC, webdotG commented on index.html
> +      <li><img src="" alt="html academy logo"></li>
fix

2020-09-30 13:20 UTC, webdotG commented on index.html
> +      <li><img src="" alt="mishka logo"></li>
fix

2020-09-30 13:20 UTC, webdotG commented on index.html
> +      <button></button>
кнопка закрытия поп-апа

2020-09-30 13:20 UTC, webdotG commented on index.html
> +    <li><a href="#"><img src="" alt="vk"></a></li>
fix

2020-09-30 13:21 UTC, webdotG commented on index.html
> +    <li><a href="#"><img src="" alt="facebook"></a></li>
fix

2020-09-30 13:21 UTC, webdotG commented on index.html
> +    <li><a href="#"><img src="" alt="instagram"></a></li>
fix

2020-09-30 13:27 UTC, zeckson approved these changes
Отлично! Погнали дальше!

2020-09-30 13:27 UTC, zeckson commented on index.html
> +      <button>X</button>
Вот теперь хорошо)

2020-09-30 13:27 UTC, merged