add img&fonts
zeckson/htmlacademy-nerds pull request #2
Opened 2020-09-30 15:58 UTC by webdotG

2020-09-30 18:54 UTC, zeckson requested changes
Если картинка не полупрозрачная и она занимает больше 50КБ, то это повод задуматься, что формат должен быть не `png`, a `jpg`.
Обрати внимание на слудющие картинки:
- img/map.png 
- img/nerds-illustration.png 
- img/nerds-index-slide1.png
- img/nerds-index-slide2.png
- img/nerds-index-slide3.png

2020-09-30 18:54 UTC, zeckson commented on css/style.css
> +  font-family: Roboto Arial sans-serif;
По [стандарту](https://developer.mozilla.org/ru/docs/Web/CSS/font-family) значения свойства `font-family` задаются через запятую.

2020-09-30 18:54 UTC, zeckson commented on css/style.css
> +  font-family: RobotoMedium Arial sans-serif;
По [стандарту](https://developer.mozilla.org/ru/docs/Web/CSS/font-family) значения свойства `font-family` задаются через запятую.

2020-09-30 18:54 UTC, zeckson commented on css/style.css
> +  font-family: RobotoMedium Arial sans-serif;
По [стандарту](https://developer.mozilla.org/ru/docs/Web/CSS/font-family) значения свойства `font-family` задаются через запятую.

2020-09-30 18:54 UTC, zeckson commented on css/style.css
> +  font-family: RobotoBold Arial sans-serif;
По [стандарту](https://developer.mozilla.org/ru/docs/Web/CSS/font-family) значения свойства `font-family` задаются через запятую.

2020-09-30 18:54 UTC, zeckson commented on css/style.css
> +  color: rgba(0, 0, 0, 1);
Обычно цвет с прозрачностью используют для полупрозрачного цвета. Для непрозрачного цвета можно использовать `<hex-color>` (16-ричную кодировку, например #000) или именованый цвет, например `black`.  Так проще читать стили и ориентироваться в цветах)

2020-09-30 18:54 UTC, zeckson commented on index.html
> +      <li><a href="#"><img src="img/cart-icon.svg" alt="cart img">Корзина</a></li> <!-- ВОПРОС вставить так или бэкграундом? -->
Обычно используют такое правило для картинок, если картинку убрать и смысл не поменяется, то можно сделать её бэкграундом.
Например, тут, если пропадёт иконка корзины, то пользователь всё равно поймёт по надписи корзина, что это корзина и можно убрать.
Если оставить ничего страшного не произойдёт, а вот если убрать лишнее  может быть хуже.
Так что тут на твоё усмотрение, как тебе будет проще это сврестать.

2020-09-30 22:58 UTC, webdotG commented on index.html
> +      <li><a href="#"><img src="img/cart-icon.svg" alt="cart img">Корзина</a></li> <!-- ВОПРОС вставить так или бэкграундом? -->
в задании было указано: указать цвет

2020-09-30 22:59 UTC, webdotG commented on css/style.css
> +  font-family: RobotoBold Arial sans-serif;
fix

2020-09-30 23:40 UTC, webdotG commented on css/style.css
> +  font-family: Roboto Arial sans-serif;
не могу посмотреть или пока не знаю как оценить размер импорта картинок в фигме
ответ на пердыдущий комент
fix

2020-09-30 23:41 UTC, webdotG commented on css/style.css
> +  font-family: RobotoMedium Arial sans-serif;
fix

2020-09-30 23:41 UTC, webdotG commented on css/style.css
> +  font-family: RobotoMedium Arial sans-serif;
fix

2020-09-30 23:41 UTC, webdotG commented on css/style.css
> +  font-family: RobotoBold Arial sans-serif;
fix

2020-09-30 23:43 UTC, webdotG commented on css/style.css
> +  color: rgba(0, 0, 0, 1);
мне было проще импортировать знчения из figma была возможность импорта в hex но я решил в rgdba

2020-09-30 23:45 UTC, webdotG commented on index.html
> +      <li><a href="#"><img src="img/cart-icon.svg" alt="cart img">Корзина</a></li> <!-- ВОПРОС вставить так или бэкграундом? -->
пока не решил как лучше, позлнее вернусь к  этому моменту

2020-10-01 14:50 UTC, zeckson commented on index.html
> +      <li><a href="#"><img src="img/cart-icon.svg" alt="cart img">Корзина</a></li> <!-- ВОПРОС вставить так или бэкграундом? -->
не поянл про цвет... =(
даваой тогда осавим пока так как есть и уберём комментарий

2020-10-01 15:00 UTC, zeckson requested changes
Почему в разметке нет картинки карты?
Почему в этом блоке не подключены картинки?
```
    <ul>
      <li><img src="http://placehold.it/209x90" alt="html academy logo"></li>
      <li><img src="http://placehold.it/209x90" alt="borodinsky logo"></li>
      <li><img src="http://placehold.it/209x90" alt="pink logo"></li>
      <li><img src="http://placehold.it/209x90" alt="mishka logo"></li>
    </ul>
```
Почему у картинко не заданы ширина и высота?

2020-10-01 15:00 UTC, zeckson commented on css/style.css
> +  font-family: RobotoMedium, rial sans-serif;
Ошибка

2020-10-01 15:00 UTC, zeckson commented on index.html
> +    <a href="#"><img src="img/nerds-logo.svg" alt="Nerds logo"></a>
упустил момент. если ты решил использовать большие картинки, то тогда нужно явно указать размер `width` и `height` чтобы вёрстка не "плыла" пока загружаются картинки

2020-10-01 15:00 UTC, zeckson commented on index.html
>      <li><a href="#"><img src="http://placehold.it/21x21" alt="instagram"></a></li>
картинка не подключена
и выше ещё две картинки

2020-10-01 15:00 UTC, zeckson commented on index.html
>        <li>
Где картинка?

2020-10-01 15:00 UTC, zeckson commented on index.html
>        <li>
Где картинка?

2020-10-01 15:00 UTC, zeckson commented on index.html
>        <li>
Где картинка?

2020-10-01 15:02 UTC, zeckson commented
Давай особо большие изображения сконвертируем в jpg, например при помощи сервиса https://png2jpg.com/
Сконверитировать надо следующие картинки:
```
- img/map.png
- img/nerds-illustration.png
- img/nerds-index-slide1.png
- img/nerds-index-slide2.png
- img/nerds-index-slide3.png
```

2020-10-01 15:03 UTC, zeckson commented on css/style.css
> +  font-family: RobotoMedium, Arial sans-serif;
Не хватает запятой

2020-10-01 15:04 UTC, zeckson commented on css/style.css
> +  font-family: RobotoBold, Arial sans-serif;
Не хватает запятой

2020-10-01 16:49 UTC, webdotG commented on index.html
> +      <li><a href="#"><img src="img/cart-icon.svg" alt="cart img">Корзина</a></li> <!-- ВОПРОС вставить так или бэкграундом? -->
убрал

2020-10-01 16:56 UTC, webdotG commented on css/style.css
> +  font-family: RobotoMedium, rial sans-serif;
ошибку исправил, карту собирался вставлять бэкграундом картинки лого вставил

2020-10-01 16:57 UTC, webdotG commented on index.html
> +    <a href="#"><img src="img/nerds-logo.svg" alt="Nerds logo"></a>
исправил

2020-10-01 16:59 UTC, webdotG commented on index.html
>      <li><a href="#"><img src="http://placehold.it/21x21" alt="instagram"></a></li>
исправил

2020-10-01 16:59 UTC, webdotG commented on index.html
>        <li>
думал ставить бэкграундом

2020-10-01 17:01 UTC, webdotG commented on index.html
>        <li>
думал ставить бэкграундом

2020-10-01 17:01 UTC, webdotG commented on index.html
>        <li>
думал ставить бэкграундом

2020-10-01 17:02 UTC, webdotG commented on css/style.css
> +  font-family: RobotoMedium, Arial sans-serif;
исправил

2020-10-01 17:02 UTC, zeckson commented on index.html
>        <li>
ok

2020-10-01 17:02 UTC, webdotG commented on css/style.css
> +  font-family: RobotoBold, Arial sans-serif;
исправил

2020-10-01 17:02 UTC, zeckson commented on index.html
>        <li>
ok

2020-10-01 17:02 UTC, zeckson commented on index.html
>        <li>
ok

2020-10-01 17:03 UTC, zeckson commented on css/style.css
> +  font-family: RobotoMedium, rial sans-serif;
Как карту можно вставить бэкграундом? Это же не декоративный элемент =(

2020-10-01 18:23 UTC, zeckson requested changes
Давай ещё подсожмём изображения при помощи сервиса https://png2jpg.com/ru/
Фигма похоже совсем не сжимает изображения при сохранении.

2020-10-01 18:23 UTC, zeckson commented on css/style.css
> +  font-family: Roboto Arial sans-serif;
Ошибка

2020-10-01 18:23 UTC, zeckson commented on css/style.css
> +  font-family: RobotoBold, Arial sans-serif;
не исправлено

2020-10-01 18:23 UTC, zeckson commented on index.html
> +       <li><a href="#"><img src="img/cart-icon.svg" alt="cart img">Корзина</a></li>
Нет размеров =(

2020-10-02 10:28 UTC, zeckson approved these changes
Огонь!

2020-10-02 10:28 UTC, merged