grid
zeckson/htmlacademy-nerds pull request #3
Opened 2020-10-02 13:37 UTC by webdotG

2020-10-03 23:23 UTC, zeckson commented on index.html
> +<header class="header">
Зачем нужен класс для `.header` у тебя может быть два `header`?

2020-10-03 23:23 UTC, zeckson commented on css/style.css
> +  margin: 0;
Зачем это свойство?

2020-10-03 23:23 UTC, zeckson commented on css/style.css
> +  background-color: white;
Зачем это свойство?

2020-10-03 23:23 UTC, zeckson commented on css/style.css
> +.main {
Зачем нужен класс `.main`? Почему нельзя использовать селектор по тегу?

2020-10-03 23:23 UTC, zeckson commented on css/style.css
> +  width: 1160px;
Зачем эта ширина?

2020-10-03 23:23 UTC, zeckson commented on css/style.css
> +  margin: 0 auto;
Что делает это центрирование?

2020-10-03 23:23 UTC, zeckson commented on index.html
>        <h2>Мы — маленькая, но гордая <br>
Давай удалим кривой символ между `я <`

2020-10-03 23:23 UTC, zeckson commented on index.html
> +        ул. Б. Конюшенная, д. 19/8<br>
Зачем `<br>`?

2020-10-03 23:23 UTC, zeckson commented on css/style.css
> +.footer {
Зачем нужен класс `.footer`? У тебя может быть два и более элемента `footer` на странице?

2020-10-03 23:23 UTC, zeckson commented on css/style.css
> +}
Не считая мелких проблем всё вроде выглядит пучком!

2020-10-03 23:33 UTC, zeckson commented on css/style.css
> +  background: white;
Зачем `white` он же и так `white`?
Ты же говорил, что у тебя на макете `#888888`? Или уже нет?

2020-10-05 14:36 UTC, webdotG commented on index.html
> +<header class="header">
нет не может, исправил

2020-10-05 14:37 UTC, webdotG commented on css/style.css
> +  margin: 0;
у боди есть отступ стандартный

2020-10-05 14:37 UTC, webdotG commented on css/style.css
> +  background-color: white;
и правда

2020-10-05 14:38 UTC, webdotG commented on css/style.css
> +.main {
можно, исправил

2020-10-05 14:39 UTC, webdotG commented on css/style.css
> +  width: 1160px;
и правда, она ведь прописана у родителя

2020-10-05 14:40 UTC, webdotG commented on css/style.css
> +  margin: 0 auto;
по факту ничего, исправил

2020-10-05 14:40 UTC, webdotG commented on index.html
>        <h2>Мы — маленькая, но гордая <br>
удалил

2020-10-05 14:42 UTC, webdotG commented on index.html
> +        ул. Б. Конюшенная, д. 19/8<br>
нужен, иначе перестраивается надпись

2020-10-05 14:42 UTC, webdotG commented on css/style.css
> +.footer {
исправил

2020-10-05 14:43 UTC, webdotG commented on css/style.css
> +  background: white;
в процессе освоения фигмы, он оказался белым

2020-10-05 16:19 UTC, zeckson requested changes

2020-10-05 16:19 UTC, zeckson commented on css/style.css
> +background: #888888;
У меня на макете цвет `#EEE`
Почему опять поменялся цвет?

2020-10-05 16:20 UTC, zeckson commented on index.html
> +        ул. Б. Конюшенная, д. 19/8<br>
я убрал нижний `<br>` и у меня ничего не перестроилось =(

2020-10-05 16:23 UTC, webdotG commented on index.html
> +        ул. Б. Конюшенная, д. 19/8<br>
нижний это невнимательность моя

2020-10-05 16:25 UTC, merged